"""
Loan-manual knowledge base — indexes the bank's Manual on Loans &
Advances (markdown export) into a local SQLite FTS5 table and answers
questions against it, fully offline.

The manual is an internal bank document: the source file stays wherever
the officer keeps it, the index lives only in the local (git-ignored)
database, and answers are generated by the local Ollama model. Nothing
leaves the machine.
"""
import pathlib
import re
import sqlite3

ROOT = pathlib.Path(__file__).resolve().parents[2]
DB   = ROOT / "db" / "cma.sqlite"

CHUNK_CHARS = 1100          # ~ a meaty paragraph or two per chunk
CHAPTER_RE  = re.compile(r"^Chapter\s*-\s*(\d+)\s*(.*)$")
PART_RE     = re.compile(r"^Part\s*-\s*(\d+)", re.IGNORECASE)

ANSWER_PROMPT = """You answer questions for a credit officer using ONLY the supplied extracts
from the bank's Manual on Loans & Advances. Rules:
- Answer from the extracts alone; if they do not cover the question, say so.
- Quote thresholds, percentages and conditions exactly as written.
- Cite the chapter shown in brackets after each extract you rely on.
- Be concise: a short answer plus the relevant conditions."""


def _ensure_table(conn):
    conn.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS manual_chunk USING fts5(
            content, chapter, part, seq UNINDEXED,
            tokenize='porter unicode61'
        )
    """)


def index_manual(path, db_path=None):
    """(Re)build the FTS index from the manual markdown. Returns chunk count."""
    text = pathlib.Path(path).read_text(encoding="utf-8", errors="replace")

    chunks = []
    chapter, part, buf = "front matter", "", []

    def flush():
        body = " ".join(" ".join(buf).split())
        if len(body) > 80:                      # skip page-furniture lines
            chunks.append((body, chapter, part))
        buf.clear()

    for line in text.splitlines():
        line = line.strip()
        m = CHAPTER_RE.match(line)
        if m:
            flush()
            chapter = f"Chapter {m.group(1)}" + (
                f" — {m.group(2).strip()}" if m.group(2).strip() else "")
            continue
        pm = PART_RE.match(line)
        if pm:
            part = f"Part {pm.group(1)}"
            continue
        if not line:
            continue
        buf.append(line.lstrip("#").strip())
        if sum(len(s) for s in buf) >= CHUNK_CHARS:
            flush()
    flush()

    with sqlite3.connect(db_path or DB) as conn:
        conn.execute("DROP TABLE IF EXISTS manual_chunk")
        _ensure_table(conn)
        conn.executemany(
            "INSERT INTO manual_chunk (content, chapter, part, seq) "
            "VALUES (?, ?, ?, ?)",
            [(c, ch, p, i) for i, (c, ch, p) in enumerate(chunks)])
    return len(chunks)


STOPWORDS = {"what", "is", "the", "a", "an", "of", "for", "to", "in", "on",
             "how", "when", "which", "are", "can", "be", "and", "or", "by"}


def search_manual(query, k=5, db_path=None):
    """Top-k manual passages: candidates by bm25 over any-term match,
    re-ranked by how many DISTINCT query terms each passage covers."""
    terms = [t for t in re.findall(r"[A-Za-z0-9]+", query.lower())
             if t not in STOPWORDS] or re.findall(r"[A-Za-z0-9]+", query.lower())
    with sqlite3.connect(db_path or DB) as conn:
        _ensure_table(conn)
        rows = conn.execute("""
            SELECT content, chapter, part, bm25(manual_chunk) AS rank
            FROM manual_chunk WHERE manual_chunk MATCH ?
            ORDER BY rank LIMIT 60
        """, (" OR ".join(f'"{t}"' for t in terms),)).fetchall()

    def coverage(content):
        low = content.lower()
        return sum(1 for t in terms if t[:6] in low)   # crude stem match

    ranked = sorted(rows, key=lambda r: (-coverage(r[0]), r[3]))
    return [{"content": r[0], "chapter": r[1], "part": r[2]}
            for r in ranked[:k]]


def manual_indexed(db_path=None):
    with sqlite3.connect(db_path or DB) as conn:
        _ensure_table(conn)
        return conn.execute("SELECT COUNT(*) FROM manual_chunk").fetchone()[0]


def ask_manual(question, k=4, db_path=None,
               model="qwen2.5:7b"):
    """Retrieve top passages and answer with the local model, cited."""
    passages = search_manual(question, k=k, db_path=db_path)
    if not passages:
        return {"answer": "", "passages": [],
                "error": "No matching passages — is the manual indexed? "
                         "(cma.py manual --index <file>)"}
    extracts = "\n\n".join(
        f"[{p['part']} {p['chapter']}]\n{p['content'][:1500]}"
        for p in passages)
    try:
        from ollama import Client
        client = Client(host="http://localhost:11434")
        resp = client.chat(
            model=model,
            messages=[{"role": "system", "content": ANSWER_PROMPT},
                      {"role": "user",
                       "content": f"EXTRACTS:\n{extracts}\n\n"
                                  f"QUESTION: {question}"}],
            options={"temperature": 0.0, "num_ctx": 8192},
        )
        answer = resp["message"]["content"]
    except Exception as e:
        return {"answer": "", "passages": passages,
                "error": f"Ollama unavailable ({e}) — showing passages only"}
    return {"answer": answer, "passages": passages, "error": ""}
